# Generated by Django 4.0.8 on 2023-05-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_company_company_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('passwd', models.CharField(max_length=50)),
            ],
        ),
    ]
